
# -------------------------------------------------------------------
# Azure Resource Deployment Configuration
# -------------------------------------------------------------------
# This YAML file is used to specify which Azure resources should be 
# deployed for a given archetype or solution. 
#
# Instructions:
# - Set a resource's value to `true` if you want it to be deployed.
# - Set a resource's value to `false` if you do not want it to be deployed.
#
# Sections:
# - `hub_internet_ingress`: Configuration for internet ingress resources in the hub (e.g., Application Gateway, Firewall, Front Door).
# - `hub_internet_egress`: Configuration for internet egress resources in the hub (e.g., Firewall).
# - `hub_intranet_ingress`: Configuration for intranet ingress resources in the hub (e.g., Application Gateway, Firewall).
# - `hub_intranet_egress`: Configuration for intranet egress resources in the hub (e.g., Firewall).
# - `management`: Management-related resources (e.g., Bastion Host, VMs).
# - `devops`: DevOps-related resources (e.g., Container Instances).
# - `project`: Project-specific resources (e.g., AKS, App Services, Key Vault, Storage Accounts, etc.).
#
# Example:
# To deploy Application Gateway in the `hub_internet_ingress` section, set `agw` to `true`:
# hub_internet_ingress:
#   agw: true
# -------------------------------------------------------------------

hub_internet_ingress:
  agw: false
  firewall_ingress: false
  frontdoor: false
hub_internet_egress:
  firewall_egress: false
hub_intranet_ingress:
  agw: false
  firewall_ingress: false
hub_intranet_egress:
  firewall_egress: false
management:
  bastion_host: false
  vm: false
devops:
  containter_instance: true
project:
  acr: true
  ai_foundry_enterprise: false
  aks_avm_ptn: false
  apim: false
  app_service: false
  app_service_intranet: false
  app_service_windows: false
  azure_open_ai: false
  container_instance: false
  cosmos_db_mongo: false
  cosmos_db_sql: false
  data_explorer: false
  event_hubs: false
  iot_hub: false
  keyvault: false
  linux_function_app: false
  logic_app: false
  mssql: false
  redis_cache: false
  search_service: false
  service_bus: false
  storage_account: false
  stream_analytics: false
  vm: false